#!/bin/bash -e

./clean

for f in `find ./ -type f -path "*/*.*" | sort`; do

  if ! ../../archsat -x +meta --meta.find=auto --meta.incr=true --infer $f --coq proof.v > log; then
    echo -e "\e[1;31m[FAIL]\e[0m $f (prover run)"
    exit 1
  fi
  if ! grep Unsat log > /dev/null; then
    echo -e "\e[1;31m[ERROR]\e[0m $f (not unsat)"
    exit 1
  fi
  if ! coqc proof.v; then
    echo -e "\e[1;31m[KO]\e[0m $f (coq check)"
    exit 1
  fi

  ./clean;
  echo -e "\e[32m[OK]\e[0m $f";

done
