
TMP_FILE=tmp.log
COQ_PROOF_FILE=proof.v
COQ_SCRIPT_FILE=script.v
COQ_TERM_FILE=term.v
COQ_NORM_FILE=norm.v
DK_TERM_FILE=term.dk
DK_NORM_FILE=norm.dk

FLAGS=-t 5s

all: $(TESTS)
	@echo -e "\033[2K\r\e[32m[OK]\e[0m [$(NAME)]"

%.res: % $(BIN)
	@echo -ne "\033[2K\r[  ] [$(NAME)] -- $<"
	@if ! $(BIN) $(FLAGS) $(OPT) $< > $(TMP_FILE); then 							\
			echo -e "\033[2K\r\e[31m[KO]\e[0m [$(NAME)] $<";			\
			echo -e "$(BIN) $(FLAGS) $(OPT) $<";									\
			cat $(TMP_FILE);																			\
			exit 1;																			\
		fi

%.sat: % $(BIN)
	@echo -ne "\033[2K\r[  ] [$(NAME)] -- $<"
	@if ! $(BIN) $(FLAGS) $(OPT) $< | tee $(TMP_FILE) | grep Unsat > /dev/null; then 							\
			echo -e "\033[2K\r\e[31m[KO]\e[0m [$(NAME)] $<";			\
			echo -e "$(BIN) $(FLAGS) $(OPT) $<";									\
			cat $(TMP_FILE);																			\
			exit 1;																			\
		fi

%.unsat: % $(BIN)
	@echo -ne "\033[2K\r[  ] [$(NAME)] -- $<"
	@if ! $(BIN) $(FLAGS) $(OPT) $< | tee $(TMP_FILE) | grep Unsat > /dev/null; then 	\
			echo -e "\033[2K\r\e[31m[KO]\e[0m [$(NAME)] $<";							\
			echo -e "$(BIN) $(FLAGS) $(OPT) $<";													\
			cat $(TMP_FILE);																			\
			exit 1;																							\
		fi

%.dk: % $(BIN)
	@echo -ne "\033[2K\r[  ] [$(NAME)] -- dk -- $<"
	@if ! $(BIN) $(FLAGS) $(OPT) --dkterm $(DK_TERM_FILE) --dknorm $(DK_NORM_FILE) $< > $(TMP_FILE); then 		\
			echo -e "\033[2K\r\e[31m[FAIL]\e[0m [$(NAME)] $<";											\
			echo -e "$(BIN) $(FLAGS) $(OPT) --dkterm $(DK_TERM_FILE) --dknorm $(DK_NORM_FILE) $<"; \
			cat $(TMP_FILE);																			\
			exit 1;																											\
		fi
	@if ! dkcheck -I ../../static $(DK_TERM_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[dkterm]\e[0m [$(NAME)] $<";										\
			echo -e "dkcheck -I static $(DK_TERM_FILE)";							\
			exit 1;																											\
		fi
	@if ! dkcheck -I ../../static $(DK_NORM_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[dknorm]\e[0m [$(NAME)] $<";										\
			echo -e "dkcheck -I static $(DK_NORM_FILE)";							\
			exit 1;																											\
		fi


%.coq: % $(BIN)
	@echo -ne "\033[2K\r[  ] [$(NAME)] -- coq -- $<"
	@if ! $(BIN) $(FLAGS) $(OPT) --coq $(COQ_PROOF_FILE) --coqscript $(COQ_SCRIPT_FILE) $< > $(TMP_FILE); then 		\
			echo -e "\033[2K\r\e[31m[FAIL]\e[0m [$(NAME)] $<";											\
			echo -e "$(BIN) $(FLAGS) $(OPT) --coq $(COQ_PROOF_FILE) --coqscript $(COQ_SCRIPT_FILE) $<"; \
			cat $(TMP_FILE);																			\
			exit 1;																											\
		fi
	@if ! coqc $(COQ_PROOF_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[coq]\e[0m [$(NAME)] $<";										\
			echo -e "coqc $(COQ_PROOF_FILE)";							\
			exit 1;																											\
		fi
	@if ! coqc $(COQ_SCRIPT_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[coq]\e[0m [$(NAME)] $<";										\
			echo -e "coqc $(COQ_SCRIPT_FILE)";							\
			exit 1;																											\
		fi

%.coqfull: % $(BIN)
	@echo -ne "\033[2K\r[  ] [$(NAME)] -- coq -- $<"
	@if ! $(BIN) $(FLAGS) $(OPT) --coq $(COQ_PROOF_FILE) --coqscript $(COQ_SCRIPT_FILE) --coqterm $(COQ_TERM_FILE) --coqnorm $(COQ_NORM_FILE) $< > $(TMP_FILE); then 		\
			echo -e "\033[2K\r\e[31m[FAIL]\e[0m [$(NAME)] $<";											\
			echo -e "$(BIN) $(FLAGS) $(OPT) --coq $(COQ_PROOF_FILE) --coqscript $(COQ_SCRIPT_FILE) --coqterm $(COQ_TERM_FILE) --coqnorm $(COQ_NORM_FILE) $<"; \
			cat $(TMP_FILE);																			\
			exit 1;																											\
		fi
	@if ! coqc $(COQ_PROOF_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[coq]\e[0m [$(NAME)] $<";										\
			echo -e "coqc $(COQ_PROOF_FILE)";							\
			exit 1;																											\
		fi
	@if ! coqc $(COQ_SCRIPT_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[coq]\e[0m [$(NAME)] $<";										\
			echo -e "coqc $(COQ_SCRIPT_FILE)";							\
			exit 1;																											\
		fi
	@if ! coqc $(COQ_TERM_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[coqterm]\e[0m [$(NAME)] $<";										\
			echo -e "coqc $(COQ_TERM_FILE)";							\
			exit 1;																											\
		fi
	@if ! coqc $(COQ_NORM_FILE) &> /dev/null; then											\
			echo -e "\033[2K\r\e[31m[coqnorm]\e[0m [$(NAME)] $<";										\
			echo -e "coqc $(COQ_NORM_FILE)";							\
			exit 1;																											\
		fi

clean:
	rm -rf *.res *.sat *.unsat *.coq $(TMP_FILE) *$(DK_TERM_FILE)* *$(DK_NORM_FILE)* *$(COQ_PROOF_FILE)* *$(COQ_SCRIPT_FILE)* *$(COQ_TERM_FILE)* *$(COQ_NORM_FILE)* *.vo *.glob

