
BIN=../archsat
OPT=
NAME=prove/poly
TESTS= \
	$(patsubst %,%.coq,$(shell find . -name '*.smt2' -o -name '*.p' | sort -n)) \
	$(patsubst %,%.dk,$(shell find . -name '*.smt2' -o -name '*.p' | sort -n))

include ../Makefile.shared

